### PR TITLE
Added input validation to prevent adding blank tasks

### PR DESCRIPTION
**Pull request by pandey22**
- Trim task input value to remove leading and trailing spaces
- Display an alert if the task field is left blank or contains only spaces
- Ensure tasks are only added to the list if they have non-blank content

### CODE REVIEW

**Comment by mukulchauuhan** [comment]
I am sorry @pandey22. I will soon be reviewing your code and gonna be merging it if it meets the requirements. By the way brother 'Thankyou' for your valuable contribution😊

**Comment by pandey22** [comment]
Sure ! Do let me know if the code is appropriate or not .

**Comment by pandey22** [comment]
Hey @mukulchauuhan , It's been a while , could you let me know whether the code suggested is appropriate or not.

**Review by mukulchauuhan — APPROVED** [review]

**Comment by mukulchauuhan** [comment]
Thanks for your contribution man. The concept of using .trim() was on point. Keep going :)

**Pull request merged**
